name: stonks
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - numpy
  - pyyaml
  - matplotlib
  - cudatoolkit
  - praw
  - pandas
  - python-dotenv
  - lxml
  - nltk
  - alive-progress
  - yfinance
  - tensorflow
  - tensorflow-gpu
  - comet_ml
  # - pip:
  #     - sklearn

