name: stonks
channels:
  - conda-forge
  - nvidia
dependencies:
  - numpy
  - pyyaml
  - matplotlib
  - praw
  - pandas
  - python-dotenv
  - lxml
  - nltk
  - alive-progress
  - yfinance
  - tensorflow
  - pip:
      - sklearn
      - comet_ml
